### PR TITLE
Add carbon footprint

### PR DESCRIPTION
**Pull request by dgrammatiko**
This PR adds a carbon key in the lighthouse results. The formula comes from https://gitlab.com/wholegrain/carbon-api-2-0 (their website is here: https://www.websitecarbon.com).

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@zachleat let me know what you think

**Comment by zachleat** [comment]
Hey @dgrammatiko I love this idea!

Can you link directly to the formula? What are the units of this formula result? And might it belong better higher up in the output? Seems unrelated to `lighthouse`

**Comment by dgrammatiko** [comment]
The code for the calculation was taken from here: https://github.com/aberforthQ/puppeteer-split-test/blob/d7e49b1ef0c61bbabb2c2c160c898eb58187471a/public/index.html#L181-L186

The formula that www.websitecarbon.com is using can be found here:
https://gitlab.com/wholegrain/carbon-api-2-0/-/blob/master/includes/carbonapi.php#L337-389
But it is depending in many values that are fetched from their db.

To compare the 2 different formulas I monkey patched the test.js (it expects that the proposed change in this PR is in place):

```js
// We need to fetch some data
const axios = require('axios');

const PerfLeaderboard = require("../.");

(async function () {
  let urls = [
    "https://www.gatsbyjs.org/",
    "https://www.11ty.dev/",
    // "https://vuejs.org/",
    // "https://reactjs.org/",
    // "https://nextjs.org/",
    // "https://amp.dev/",
    // "https://jekyllrb.com/",
    // "https://nuxtjs.org/",
    // "https://gridsome.org/",
    // "https://svelte.dev/",
    // "https://gohugo.io/",
    // "https://redwoodjs.com/"
  ];

  console.log(await PerfLeaderboard(urls, 3));

  [urls].forEach(url =>
    axios.get(`https://api.websitecarbon.com/site?url=${url}`)
      .then(resp => resp.json())
      .then(data => console.log(data))
      .catch(e => console.log(e))
  );
})();
```

Since www.websitecarbon.com actually has a public API `https://api.websitecarbon.com/site?url=${url}` maybe you don't have to roll your own formula and just do an additional fetch?

> What are the units of this formula result

The units for the derived value should be  `grams of CO2/page`

> Seems unrelated to lighthouse

Yes, probably should be moved one level up

**Comment by dgrammatiko** [comment]
I'm closing this one as I think #7 is a better approach

**Pull request closed without merging**
